version: '3.8'

services:
  # Movie Recommendation API - Main Application
  movie-rec-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: movie-rec-app
    ports:
      - "8001:8001"  # Main FastAPI port
      - "8002:8002"  # Prometheus metrics port
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://localhost:5000}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    volumes:
      - ../models:/app/models:ro  # Read-only access to models
      - ../data:/app/data:ro      # Read-only access to data
      - ../logs:/app/logs         # Writable logs directory
      - ../config:/app/config:ro  # Configuration files
    networks:
      - movie-rec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - redis

  # Redis for caching recommendations and session data
  redis:
    image: redis:7-alpine
    container_name: movie-rec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - movie-rec-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: movie-rec-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/usr/share/nginx/html/static:ro
    networks:
      - movie-rec-network
    restart: unless-stopped
    depends_on:
      - movie-rec-app

volumes:
  redis_data:

networks:
  movie-rec-network:
    driver: bridge
